### ISSUE TITLE
task crash if thermo file not found

### ISSUE THREAD

**Issue by maf70** [maf70/Woodie#1]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/pi/Woodie/hw.py", line 72, in run
    f=open("/sys/bus/w1/devices/"+self.device+"/w1_slave","r")
IOError: [Errno 2] No such file or directory: '/sys/bus/w1/devices/28-0417c1418bff/w1_slave'

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/pi/Woodie/hw.py", line 72, in run
    f=open("/sys/bus/w1/devices/"+self.device+"/w1_slave","r")
IOError: [Errno 2] No such file or directory: '/sys/bus/w1/devices/28-0517c1392fff/w1_slave'

**Comment by maf70** [comment]
Set exception handler to IOError
